---
title: "FJP"
author: "Anastácio Ferreira"
date: "2024-02-23"
output: html_document
---

1. Abrir base de dados
```{r}
library(readr)
dados <- read_delim("C:/Users/Universidade Federal/Downloads/DadosConsulta.csv", delim = ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
```

```{r}
names(dados) <- c("cod", "mun", "ut", "mm", "pm")

dados <- dados[-1,]

library(dplyr)
dados <- dados %>%
    mutate_at(vars(c("cod", "ut", "mm", "pm")), ~as.numeric(gsub(",", ".", .)))

dados <- dados[,-2]
```


```{r}
summary(dados$ut)
summary(dados$mm)
summary(dados$pm)

hist(dados$ut, main = "Histograma de ut", xlab = "ut", ylab = "Frequência")
hist(dados$mm, main = "Histograma de mm", xlab = "mm", ylab = "Frequência")
hist(dados$pm, main = "Histograma de pm", xlab = "pm", ylab = "Frequência")
```

#Mapas
```{r}
library(geobr)
library(sf)
mun_mg <- read_municipality(code_muni=31, year=2018)
```

```{r}
dataset = left_join(mun_mg, dados, by=c("code_muni"="cod"))
```

```{r}
library(ggplot2)
ggplot() +
  geom_sf(data = dataset, aes(fill = ut), color = NA, size = 0.15) +
  labs(title = "Taxa de Mortalidade por Câncer de Colo de Útero", 
       caption = NULL, size = 8) +
  scale_fill_distiller(palette = "RdGy", limits = c(0.0, 100), name = "Code_muni") +
  theme_minimal()
  
ggplot() +
  geom_sf(data = dataset, aes(fill = mm), color = NA, size = 0.15) +
  labs(title = "Taxa de Mortalidade por Câncer de Mama", 
       caption = NULL, size = 8) +
  scale_fill_distiller(limits = c(0.0, 100)) +
  theme_minimal()
  
ggplot() +
  geom_sf(data = dataset, aes(fill = pm), color = NA, size = 0.15) +
  labs(title = "Taxa de Mortalidade por Câncer de Pulmão", 
       caption = NULL, size = 8) +
  scale_fill_distiller(palette = "Greens", limits = c(0.0, 100), name = "Code_muni") +
  theme_minimal()
```

# Calculando o I de Moran
```{r}
## Transformando objeto sf em sp
library(sp)
dataset_sp <- sf:::as_Spatial(dataset$geom)

## Calculando a contiguidade queen
library(spdep)
queen <- spdep::poly2nb(dataset_sp, queen=T)

## Transformando os pesos em formato nb
peso <- nb2listw(queen, style = "W")

## Cálculo e teste do Indice Global de Moran
moran.test(dataset$ut,peso, alternative="two.sided")
moran.test(dataset$mm,peso, alternative="two.sided")
moran.test(dataset$pm,peso, alternative="two.sided")
```
